steps:
  - name: node:16-slim
    entrypoint: yarn
    args: ['install']
  - name: node:16-slim
    entrypoint: yarn
    args: ['build']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--project=bandoku', '--no-promote']
